[package]
name = "pgp-words"
version = "0.2.1"
authors = ["Thibault Polge <thibault@thb.lt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
err-derive = "0.2.4"
